# Generated by Django 5.1 on 2024-08-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=100)),
                ('next_of_kin', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('hear_about_us', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state_of_origin', models.CharField(max_length=50)),
                ('course_duration', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('instructor', models.CharField(max_length=100)),
                ('type_of_training', models.CharField(max_length=50)),
                ('payment_plan', models.CharField(max_length=50)),
                ('registering_officer', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
